### ISSUE TITLE
MongoDB connection is not close.

### ISSUE THREAD

**Issue by hangum** [kornilova-l/mongo-jdbc-driver#3]
Using the database and close the connection does not close.
Please check. 

As shown below, I turned 10 threads and ended all.
10 deamon thread are alive.

![image](https://user-images.githubusercontent.com/1335915/69603284-7fc76b80-105d-11ea-83a5-c75b23edd8ea.png)

Example source.
`public class MongoDBTest implements Runnable {
	public static void main(String[] args) {
		for(int i=0; i<10; i++) new Thread(new MongoDBTest()).start();
	}

	@Override
	public void run() {
		System.out.println("===== starting test...  source of github");
		String url = "mongodb://test@127.0.0.1:32769/admin";
 
		Connection con = null;
		Statement stmt = null;
		ResultSet rs = null;
        try {
            Class.forName("com.dbschema.MongoJdbcDriver");
            con = DriverManager.getConnection(url, null, null);
            con.setSchema("test2");
            stmt = con.createStatement();
            rs = stmt.executeQuery("db.getCollection('dbtype').find({})");//db.module_map.find()");//"db.getCollection('system.users').find({})");
            
            ResultSetMetaData rsm = rs.getMetaData();
            System.out.println("\t column count: " + rsm.getColumnCount());
            System.out.println("\t column name is " + rsm.getColumnDisplaySize(1));
            System.out.println("\t get row is " + rs.getRow());
            
            System.out.println("\t table name is " + rsm.getTableName(1));

            while(rs.next()) {
                Object obj = rs.getObject(1);
                if(obj instanceof DBCollection) {
                    System.out.println("\t dbcollection");
                } else {
                    System.out.println("\t" + obj.getClass().getName());
                }
                System.out.println("==> " + obj.toString());
            }

        } catch(Exception e) {
            e.printStackTrace();
        } finally {
        	try { if(rs != null) rs.close(); } catch(Exception e) {e.printStackTrace();}
        	try { if(stmt != null) stmt.close(); } catch(Exception e) {e.printStackTrace();}
        	try { if(con != null) con.close(); } catch(Exception e) {e.printStackTrace();}
        }
        
        System.out.println("====== end test");
	}
}
 `

**Comment by kornilova-l** [comment]
@hangum you are right
Thank you for catching the problem!
I'll fix it ASAP

**Comment by kornilova-l** [comment]
Closed by 9bbd9ad5b1d186ac46dc30ff0187b2748d6417be

Also note that now standalone jar is compiled, so you do not need `mongo-java-driver-3.11.0.jar`. But you can undo it by reverting commit cff2bf768413819d153bedba4c1134a171a5a0e4

**Comment by hangum** [comment]
@kornilova-l  thanks a lot.
